#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          init-ksz8794
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO
DESC=init-ksz8794

. /lib/lsb/init-functions

SPI=/sys/bus/spi/devices
SWREG=$SPI/spi0.0/sw/reg
CONFIG=0xff

case $1 in
	start)
		# set register to enable KSZ8794 switch
		log_daemon_msg "echo 0x56=$CONFIG > $SWREG"
		echo 0x56=$CONFIG > $SWREG
		;;
	*)
		;;
esac
